
export default function About() {
    return (
      <>
      <Head>
        <title>Create React App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>Helloo</code>
          </p> 
          <p>hello</p>
          </div>
      </main>

    <div>About</div>
  </>
  )
};

