import Head from 'next/head'

import styles from '@/styles/globals.css'

import 'pages/index.js';

NavBar();

export default function About() {
  return (
    <>
    <Head>
      <title>About</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>Helloo</code>
          </p> 
          <p>About</p>
          </div>
      </main>
    </>
  )
}